# Name of workflow
name: Git_Test

# Trigger the workflow on push or pull request
on: 
  push

  jobs:
    build:
    name: Test Job

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - run: make lint
      
